version: '3.7'

services:
  backend:
    volumes:
      - ./backend/src:/backend/src
      - node_modules_backend:/backend/node_modules
    ports:
      - 5000:5000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
      - node_modules_frontend:/frontend/node_modules
    ports:
      - '8080:8080'
