version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  backend:
    build: ./backend
    restart: always
    container_name: backend-terraformation
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    container_name: frontend-terraformation
    restart: unless-stopped
    build:
      context: ./frontend

volumes:
  mongodb_data_container:
  node_modules_backend:
  node_modules_frontend:
