version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    restart: always
    container_name: backend-terraformation
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    container_name: frontend-terraformation
    restart: unless-stopped
    build:
      context: ./frontend

volumes:
  #   pgdata:
  node_modules_backend:
  node_modules_frontend:
